config/routes.rb
Rails.application.routes.draw do

  get 'community_resources/new'

  root 'static_pages#home'
  get '/home', to: 'static_pages#home'
  get '/resources', to: 'resources#resources'
  get '/contact', to: 'contacts#new'
  get '/volunteer', to: 'static_pages#volunteer'
  
  get '/fr_home', to: 'static_pages#fr_home'
  get '/fr_resources', to: 'resources#fr_resources'
  get '/fr_volunteer', to: 'static_pages#fr_volunteer'

  get '/sp_home', to: 'static_pages#sp_home'
  get '/sp_resources', to: 'resources#sp_resources'
  get '/sp_volunteer', to: 'static_pages#sp_volunteer'
  

  resources :contacts, only: [:new, :create]

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/community_resource.rb
#The one line lets the database have tags for its entries
class CommunityResource < ApplicationRecord
  acts_as_taggable_on :tags
end

app/models/contact.rb
=begin

#############################
##   ABOUT THIS DOCUMENT   ##
##   Updated May 6, 2020   ##
#############################

This file controls what the email sends and what information we are getting
from the contact form.

=end



class Contact < MailForm::Base

  #Section for what information you want the email to include.
  attribute :name
  attribute :contact_info,     :validate => true
  attribute :subject,   :validate => true
  attribute :message,   :validate => true
  
  #This attribute is to prevent spam: nickname should not be filled out in real form
  attribute :nickname,  :captcha  => true

  #This section controls where the emails are sent to/from and the subject.
  #Check the mailform github page or other tutorials to see how to change how the
  #email actually is formatted in HTML if you want to change it (you'll probably
  #have to make a new HTML file).
  def headers
    {
      :subject => %(#{subject}),
      :to => "cosicontactus@gmail.com",
      :from => %(cosicontactus@gmail.com)
    }
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/contacts_controller.rb
=begin

#############################
##   ABOUT THIS DOCUMENT   ##
##   Updated May 6, 2020   ##
#############################

This file actually sends the email when the button is pressed. It also
keeps track of the possible subjects in the dropwon of the form.

=end


class ContactsController < ApplicationController
    
    def new
        @contact = Contact.new
        @subjects = ["Volunteer", "Donate", "Information on Immigrant Rights",
                     "Request a Presentation", "Other"]
    end
    
    def create
        @contact = Contact.new(params[:contact])
        @contact.request = request
        if @contact.deliver
            flash[:success] = "Message sent successfully!"
            redirect_to contact_path
        else
            flash.now[:error] = 'Cannot send message. Try again.'
            render :new
        end
    end
end

app/controllers/resources_controller.rb
class ResourcesController < ApplicationController
    
    def resources
        @resources = CommunityResource.order("category")
    end
    
    def sp_resources
    end
    
    def fr_resources
    end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
    
  def home
  end

  def volunteer
  end

  def sp_home
  end

  def sp_volunteer
  end

  def fr_home
  end

  def fr_volunteer 
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/community_resources_helper.rb
module CommunityResourcesHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/resources_helper.rb
module ResourcesHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/contacts/new.html.erb
<!-- Title (text that appears on webpage tab), language (for accessibility) -->
<!--   provided to app/views/layouts/application.html.erb-->
<% provide(:title, "Contact") %>
<% provide(:lang, "en") %>

<div style="display:block; width:100%;">
  <div class="row">

    <div style="width:50%; float: left; display: inline-block;">
      <h1> Contact us to... </h1>
      <ul>
        <li>
	  <h3>
	    Receive humanitarian assistance and information regarding
	    immigrant rights and legal strategy.
	  </h3>
	</li>
	<li>
	  <h3>
	    Volunteer professional services or personal skills and abilities.
	  </h3>
	</li>
	<li>
	  <h3>Request workshops, seminars, or public presentations.</h3>
	</li>

	<li style="list-style:none;">
	  <h3>Phone: <a href="tel:+1-641-316-6868">641-316-6868</a></h3>
	</li>
	<li style="list-style:none;">
	  <h3>
	    Email: <a href="mailto:cosicentraliowa@gmail.com">
	            cosicentraliowa@gmail.com </a>
	  </h3>
	</li>
	<li style="list-style:none;">
	  <h3>
	    First Presbyterian Church <br>
	    1025 5th Ave <br>
	    Grinnell, IA 50112
	  </h3>
	</li>
      </ul>
   </div> <!-- style="width:50%; ... -->

<!--   Start of form -->
   <div style="width:50%; float: left; display: inline-block;">
     <h1> Reach out to us... </h1>
     <h3 style="margin-left:10%;">
         <%= form_for @contact do |f| %>
         <!--   Name is not required -->
           <%= f.label :name, 'Name' %> <br>
           <%= f.text_field :name, required: false %><br><br>

           <%= f.label :contact_info, 'Email or Phone Number' %> <br>
           <p style="font-size: 0.8em; margin-top: 0px;">
	     *Please make sure this field is correct! It is the only
             place we can contact to respond to your message.
	   </p>
           <%= f.text_field :contact_info, required: true %><br><br>

           <%= f.label :subject %> <br>
           <%= f.select :subject, @subjects, :prompt => "Select one" %><br><br>

           <%= f.label :message %> <br>
           <%= f.text_area :message, as: :text %><br>

           <% f.label :nickname %> <br>
           <% f.text_field :nickname, hint: 'leave this field blank' %>

           <%= f.submit 'Send Message', class: "button" %>
         <% end %>

         <% flash.each do |key, value| %>
         <div class="alert alert-<%= key %>", style="margin-top:10px;">
	   <%= value %>
	 </div>
       <% end %>
       <%= yield %>
    </h3>
  </div> <!-- style="width:50%; ... -->
</div> <!-- class="row" -->
<!-- ???    style="display:block; width:100%;" -->

app/views/layouts/_footer.html.erb
<!--This page controls the footer and copyright information -->

<footer class="footer">

 <ul class="footer__nav">

   <li class="nav__item">
       <h2 class="nav__title">
        <a href="tel:+1-641-316-6868">641-316-6868</a></h2>
   </li>

   <li class="nav__item">
       <h2 class="nav__title"><a href="mailto:cosicentraliowa@gmail.com" >
                               cosicentraliowa@gmail.com </a></h2>
   </li>

   <li class="nav__item">
       <h2 class="nav__title">First Presbyterian Church <br> 1025 5th Ave <br>
        Grinnell, IA 50112</h2>
   </li>
   
 </ul>

 <div class="legal">
   <p>
     Copyright &copy; 2020
     Community Support for Immigrants - All Rights Reserved.
   </p>
  </div>

</footer>

app/views/layouts/_header.html.erb
<!--This page controls the logo, logo text image, and navigation bar for every page.
    Once you have added Spanish and french pages, replace logo text with just english one
    Delete "contactar" and "recursos/servicios" -->

<!DOCTYPE html>
<header role="banner">
 <a style="text-decoration:none;" href= "/home">
   <img src="assets/logo.png" width="240" alt="CoSI Logo", id="navLogo">
   <img src="assets/logoText"  width="400"
	alt"COMMUNITY SUPPORT FOR IMMIGRANTS; COMUNIDAD DE APOYO PARA IMMIGRANTES",
	id="Logotext">
 </a>
</header><!-- role="banner" -->

<header class="navbar">
  <div class="container">
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li class="navlist">
	  <%= link_to "HOME", root_path, class: "short" %>
	  <!-- "short" class makes links same height as those with
               Spanish. Delete this class if you remove the Spanish. -->
	</li>

        <li class="navlist">
	  <%= link_to(resources_path) do %>
            RESOURCES/SERVICES
            <br />
            <p2> RECURSOS/SERVICIOS </p2>
          <% end %>
        </li>

        <li class="navlist">
	  <%= link_to(contact_path) do %>
            CONTACT
            <br />
            <p2> CONTACTAR </p2>
          <% end %>
        </li>

        <li class="navlist">
	  <%= link_to "VOLUNTEER/DONATE", volunteer_path, class: "short" %>
	</li>
      </ul>
    </nav>
  </div> <!-- class="container" -->
</header><!-- class="navbar" -->



<!-- *** OLD, IGNORE *** -->


  <!--
<nav>
      <ul class="navbar-nav nav navbar-inverse">
        <li class="nav-link"><%= link_to "Home", root_path %></li>
        <li class="nav-link"><%= link_to "Resources/Services", resources_path %></li>
        <li class="nav-link"><%= link_to "Contact", contact_path %></li>
        <li class="nav-link"><%= link_to "Volunteer", volunteer_path %></li>
      </ul>
</nav>
 -->



<!-- Brand and toggle get grouped for better mobile display
<header>
  <div class="logo">
    <img src="assets/logo.png" alt="CoSI Logo", id="navLogo">
  </div>
  <div class="container">
    <header class="navbar navbar-fixed-top navbar-inverse">
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home", root_path %></li>
        <li><%= link_to "Resources/Services", resources_path %></li>
        <li><%= link_to "Contact", contact_path %></li>
        <li><%= link_to "Volunteer", volunteer_path %></li>
      </ul>
    </nav>
  </div>
</header>
-->

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!-- This file sets up the layout for each of the pages in the website.
      Right now the main purpose of it is to make the site more searchable
      in Google - this needs to be improved (see README)  -->


<!DOCTYPE html>
<html lang="<%= yield(:lang) %>"> <!-- Language, for accessibility purposes -->
  <head>
    <title><%= yield(:title) %> | CoSI</title> <!-- provided by each page -->
    <%= csrf_meta_tags %>

	<!-- meta tags for google site verification DO NOT REMOVE: for future SEO feel free to add on tags and modify the description to improve page ranking in google search  -->
    <meta name="google-site-verification"
	  content="XtY9hV8WgWGfVFx6U8clKQkzht17KJtIs44BGubkYVA" />
    <meta name=”description”
	  content=”CoSI (Community Support for Immigrants) promotes a welcoming,
	  respectful, and safe environment for international persons living or
	  working in central Iowa. ”>

    <%= stylesheet_link_tag 'application', media: 'all',
                                           'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application',
	                       'data-turbolinks-track': 'reload' %>
    <%= render 'layouts/shim' %>
  </head>

  <body>
    <%= render 'layouts/header' %>

    <div class="container">
      <%= yield %> <!-- page content -->
      <%= render 'layouts/footer' %>
    </div>
  </body>
</html>

app/views/resources/fr_resources.html.erb
<% provide(:title, "fr-Resources/Services") %>
<% provide(:lang, "fr") %>
<h1>StaticPages#fr-resources</h1>
<p>Find me in app/views/static_pages/fr-resources.html.erb</p>

app/views/resources/resources.html.erb
<!--This page controls the resources layout-->

<!-- Title (text that appears on webpage tab), language (for accessibility) -->
<!--   provided to app/views/layouts/application.html.erb-->
<% provide(:title, "Resources/Services") %>
<% provide(:lang, "en") %>

<div class="row">

  <!-- *** Left Sidebar (Navbar) *** -->
  <div class="column categories">
    <ul class="list data">
      <!-- Title of sidebar -->
      <li class="bold", style="margin-bottom:4%;">Jump to...</li>

      <!-- Sidebar links (resource categories) -->
      <li>
	<a href="#Community">
	  Community Resources <br> <c> Recursos en la Comunidad </c>
	</a>
      </li>
      <br>
      
      <li>
	<a href="#Education">
	  Education about Immigration <br> <c> Educación sobre Inmigración <c>
        </a>
      </li>
      <br>
      
      <li>
	<a href = "#Language">
	  Language Assistance <br> <c> Ayuda con la Lengua </c>
	</a>
      </li>
      <br>
      
      <li>
	<a href = "#Legal">Legal Assistance <br> <c> Ayuda legal </c> </a>
      </li>
    </ul>
  </div> <!-- class="column categories" -->

  <!-- *** Main Text (Resources) - From Database *** -->
  <div class="column resources">
    <ul class="list data border-left">
      <% count = 0 %> <!-- Initialize count -->

      <!-- *** Start Loop: For each resource in database... ***-->
      <% @resources.each do |resource|%>

        <!-- Display category name if new category -->
        <!-- id is the first word in the category name (used to jump to this
                point when user clicks on category on left) -->
        <% if count==0 || @resources[count-1].category != @resources[count].category%>
          <li class="bold category" id="<%= resource.category.split.first%>">
            <%= resource.category %>
          </li>
        <%end%>

        <!-- List variables for each resource, if not empty -->
        <!--   Order of display: Name, Description (with link if exists),
               Link message, Contact person, Email, Phone number, Address -->
        <% if resource.link != nil && resource.splink != nil%>
          <li style="font-weight: bold;"> <!-- If spanish link exists -->
	    <%= link_to resource.name, resource.link, target: :_blank %>
	    / <c><%= link_to "Lista de Recursos en la Comunidad",
		     resource.splink, target: :_blank %></c>
	    <!-- This needs to be replaced with generic code. Probably requires
                 creating a database table with Spanish name. See
                 https://stackoverflow.com/questions/4834809/adding-a-column-to-an-existing-table-in-a-rails-migration -->
  	  </li>
	<% elsif resource.link != nil %> <!-- If no Spanish, display English -->
	  <li style="font-weight: bold;">
	    <%= link_to resource.name, resource.link, target: :_blank %>
  	  </li>
        <% else %> <!-- If no link exists, just display resource name -->
	  <li style="font-weight: bold;"><%=resource.name%></li>
        <% end %>

        <% if resource.description != nil%>
            <li><%= resource.description%></li>
        <%end%>

	<!-- If resource link in Spanish and English, display instructions -->
        <% if resource.link != nil && resource.splink != nil %>
           <li>Click the resource title to access. Also available in Spanish,
	   click título en español para acceder a este recurso.</li>
	<% elsif resource.link != nil %> <!-- Instructions if only English -->
	   <li>Click the resource title to access.</li>
        <%end%> <!-- else no link, don't display message. -->

        <% if resource.contact != nil%>
          <li><b>Contact Person: </b><%=resource.contact%></li>
        <%end%>

        <% if resource.email != nil%>
          <li><b>Email: </b>
     	    <a href="mailto:<%=resource.email%>"> <%=resource.email%></a>
          </li> <!-- email is clickable -->
        <%end%>

        <% if resource.phone != nil%>
          <li><b>Phone Number: </b>
	    <a href="tel:+1-<%= resource.phone%>"><%= resource.phone%></a></li>
        <%end%> <!-- phone is clickable, appends +1 to support calls from
                     phones originating outside the U.S., a likely scenario -->

        <% if resource.address != nil%>
          <li><b>Address: </b><%= resource.address%></li>
        <%end%>
	
        <br>
      
        <%count = count + 1%> <!-- increment count -->
      <%end %> <!-- *** End Loop *** -->
    </ul>
  </div> <!-- class="column resources" -->
  
</div> <!-- class="row" -->

app/views/resources/sp_resources.html.erb
<% provide(:title, "sp-Resources/Services") %>
<% provide(:lang, "sp") %>
<h1>StaticPages#sp-resources</h1>
<p>Find me in app/views/static_pages/sp-resources.html.erb</p>

app/views/static_pages/fr-contact.html.erb
<h1>StaticPages#fr-contact</h1>
<p>Find me in app/views/static_pages/fr-contact.html.erb</p>

app/views/static_pages/fr-home.html.erb
<h1>StaticPages#fr-home</h1>
<p>Find me in app/views/static_pages/fr-home.html.erb</p>

app/views/static_pages/fr-resources.html.erb
<h1>StaticPages#fr-resources</h1>
<p>Find me in app/views/static_pages/fr-resources.html.erb</p>

app/views/static_pages/fr_home.html.erb
<% provide(:title, "fr-Home") %>
<% provide(:lang, "fr") %>
<h1>StaticPages#fr-home</h1>
<p>Find me in app/views/static_pages/fr-home.html.erb</p>

app/views/static_pages/fr_volunteer.html.erb
<% provide(:title, "fr-Volunteer or Donate") %>
<% provide(:lang, "fr") %>
<h1>StaticPages#fr-volunteer</h1>
<p>Find me in app/views/static_pages/fr-volunteer.html.erb</p>

app/views/static_pages/home.html.erb
<!--This page controls the homepage with links to resources and volunteer pages 
    Spanish text is in <c> which means italics -->

<!-- Title (text that appears on webpage tab), language (for accessibility) -->
<!--   provided to app/views/layouts/application.html.erb-->
<% provide(:title, "Home") %>
<% provide(:lang, "en") %>

<img src="assets/home.jpg" width="600" alt="Homepage Picture", class="centerImage",
     style="margin-top: 1%; margin-bottom: 3%;">

<h1 class="center", style="font-weight: bold;">Mission Statement</h1>
<h2 id="about">CoSI (Community Support for Immigrants) promotes a welcoming, respectful, and safe environment for immigrants living or working in central Iowa (in particular Grinnell, Tama, Brooklyn).  We provide information about the resources available to immigrants in our community as well as some assistance. We also aim at building bridges of trust, mediate attitudes of divisiveness around the topic of immigration, and reduce the impact of an immigration enforcement incident on the social fabric and economic well-being of the community. We also provide a humanitarian safety net for workers and families who live with the anxiety of possible disruption of family life, separation from minor children, detention, and potential deportation.</h2>

<div class="row">

  <div class="column home">
    <h3 class="center bold", style="font-size:1.9em;">
      <a href="/resources" class="hometitlelink">Seeking Assistance<br><i>Busca ayuda</i>
      </a>
    </h3>
    
    <ul class="list border-right">
      <li><a href="/resources#Language" class="homelink">
	   English learning / <c> Aprendizaje del inglés</c></a> 
      </li>
      
      <li><a href="/resources#Legal" class="homelink">
	   Legal assistance / <c> Ayuda legal </c></a>
      </li>
      
      <li><a href="/resources#Community" class="homelink">
	   Other support in the community / <br>
	   <c>Otros servicios de apoyo en la comunidad</c></a>
      </li>
      
      <li><a href="/resources" class="homelink">
	   Emergency planning/raid or detention response / <br>
	   <c> Plan de emergencia en caso de redada y detención</c></a>
      </li>
      
      <li><a href="/resources#Education" class="homelink">
	   Education about immigration /
	   <c>Educación sobre inmigración</c></a>
      </li>
   </ul>
  </div> <!-- "column home" -->
  
  <div class="column home">
    <h3 class="center bold", style="font-size:1.9em;">
      <a href="/volunteer" class="hometitlelink">Seeking to help</a>
    </h3>
    
    <ul class="list">
      <li><a href="/volunteer" class="homelink">Joining CoSI as a volunteer</a></li>
      <li><a href="/volunteer" class="homelink">Donating</a></li>
    </ul>
  </div> <!-- "column home" -->
  
</div> <!-- "row" -->

app/views/static_pages/sp-contact.html.erb
<h1>StaticPages#sp-contact</h1>
<p>Find me in app/views/static_pages/sp-contact.html.erb</p>

app/views/static_pages/sp-home.html.erb
<h1>StaticPages#sp-home</h1>
<p>Find me in app/views/static_pages/sp-home.html.erb</p>

app/views/static_pages/sp-resources.html.erb
<h1>StaticPages#sp-resources</h1>
<p>Find me in app/views/static_pages/sp-resources.html.erb</p>

app/views/static_pages/sp_home.html.erb
<% provide(:title, "sp-Home") %>
<% provide(:lang, "sp") %>
<h1>StaticPages#sp-home</h1>
<p>Find me in app/views/static_pages/sp-home.html.erb</p>

app/views/static_pages/sp_volunteer.html.erb
<% provide(:title, "sp-Volunteer or Donate") %>
<% provide(:lang, "sp") %>
<h1>StaticPages#sp-volunteer</h1>
<p>Find me in app/views/static_pages/sp-volunteer.html.erb</p>

app/views/static_pages/volunteer.html.erb
<!--This page controls the volunteer page-->

<!-- Title (text that appears on webpage tab), language (for accessibility) -->
<!--   provided to app/views/layouts/application.html.erb-->
<% provide(:title, "Volunteer or Donate") %>
<% provide(:lang, "en") %>

<h1 class="center bold", style="font-size:1.4em;">
     CoSI is an organization run completely by volunteers.<br>
     Any contribution greatly increases the impact the organization can have.
<h1>

<h2 class="center bold", style="font-size:1.9em; padding-top:10px">
     Volunteer Opportunities
</h2>

<ul class="list">
  <li>
    Volunteer in case of an immigration enforcement
    (donating food, preparing and serving food, translating)
  </li>

  <li>Volunteer as an interpreter or translator for Spanish or French</li>

  <li>Volunteer as part of your career as a Grinnell College student</li>

  <li>
    There are various committees within the organization you could also
    volunteer to serve on. Please contact us with your skills and interests
    if you are interested.
  </li>

  <li>
    To volunteer, please
    <a href="/contact">email us</a>
    with your skills and availability and best way to contact you.
  </li>
</ul>

<h3 class="center bold", style="font-size:1.9em; padding-top:10px">
     Donations
</h3>

<ul class="list">
  <li>
    For donations please make checks payable to CoSI and send to
    First Presbyterian Church, 1025 5th Ave, Grinnell, IA, 50112
  </li>
</ul>

<h3 class="center", style="font-size:1.9em; padding-top: 10px">
  <a href="/contact", class="volunteerlink">
    If you are interested in donating or volunteering, please <i>contact us!</i>
  </a>
</h3>